tag @a remove cp1
tag @a remove reached_cp1
tag @a remove cp2
tag @a remove reached_cp2
tag @a remove cp3
tag @a remove reached_cp3
tag @a remove cp4
tag @a remove reached_cp4
tag @a remove cp5
tag @a remove reached_cp5
tag @a remove cp6
tag @a remove reached_cp6
tag @a remove cp7
tag @a remove reached_cp7
tag @a remove cp8
tag @a remove reached_cp8
tag @a remove cp9
tag @a remove reached_cp9
tag @a remove cp10
tag @a remove reached_cp10
tag @a remove cp11
tag @a remove reached_cp11
tag @a remove cp12
tag @a remove reached_cp12
tag @a remove cp13
tag @a remove reached_cp13
tag @a remove finished
tag @a remove equipped
tag @a remove racing
tag @a remove creative